### PR TITLE
Fix position calculations for 'vertical' mode

### PR DESCRIPTION
**Pull request by mrkosima**
This PR fixes handle's position calculations for vertical mode.

### CODE REVIEW

**Comment by mrkosima** [comment]
I'm going to provide new PR with fixing vertical slider in storybook soon. 
And will put a test for this case in it. 

Can we merge this PR now and release a package, because the fix is obvious and very important for my current project?

**Comment by ljharb** [comment]
I’d prefer not to merge a fix without a regression test in the same PR.

It may be obvious looking at the diff, but it was non-obvious enough to be missed previously.

**Comment by mrkosima** [comment]
@ljharb , I've added tests, check please.

**Comment by dperyel** [comment]
Would be nice to have the fix merged soon (-;

**Comment by mrkosima** [comment]
@majapw could you please check the PR?

**Comment by mrkosima** [comment]
@ljharb could you help the PR to be merged?

**Comment by mrkosima** [comment]
@ljharb is it possible to make a 3.0.2 release with this fix?

**Comment by majapw** [comment]
Released! I will do better next time at quick turnaround. :)

**Pull request merged**
